services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      redis_bp:
        condition: service_healthy
    networks:
      - queue_bite
  redis_bp:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "${WAITLIST_REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - queue_bite

networks:
  queue_bite:
